version: '3.8'

networks:
  web:
    external: true

services:
  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server
    restart: unless-stopped
    networks:
      - web
    expose: 
    - 80
    volumes:
    - ./bw-data/:/data/ 
    environment:
    - SIGNUPS_ALLOWED=false
    - DOMAIN=https://${BITWARDEN_DOMAIN}
    labels:
    - 'traefik.enable=true'
    - "traefik.http.routers.bitwarden.entrypoints=http"
    - "traefik.http.routers.bitwarden.rule=Host(`${BITWARDEN_DOMAIN}`)"
    - "traefik.http.routers.bitwarden.middlewares=https-redirect@file"
    - "traefik.http.routers.bitwarden-secure.entrypoints=https"
    - "traefik.http.routers.bitwarden-secure.rule=Host(`${BITWARDEN_DOMAIN}`)"
    - "traefik.http.routers.bitwarden-secure.tls=true"
    - "traefik.http.routers.bitwarden-secure.tls.certresolver=http"
    - "traefik.http.routers.bitwarden-secure.service=bitwarden"
    - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
    - 'traefik.docker.network=web'
